version: "2"

services: 
    surfshark:
        image: ilteoood/docker-surfshark
        container_name: surfshark
        environment: 
            - SURFSHARK_USER=<SURFSHARKUSERNAME>
            - SURFSHARK_PASSWORD=<SURFSHARKPASSWORD>
            - SURFSHARK_COUNTRY=it
            - SURFSHARK_CITY=mil
            - CONNECTION_TYPE=udp
            - LAN_NETWORK=192.168.200.0/24
        cap_add: 
            - NET_ADMIN
        devices:
            - /dev/net/tun
        ports:
            - 9055:9091 #we open here the port for transmission, as this container will be the access point for the others
            - 8989:8989 #These are the ports for Sonarr to
        restart: unless-stopped
        dns:
            - 1.1.1.1
    service_test:
        image: byrnedo/alpine-curl
        container_name: alpine
        command: -L 'https://ipinfo.io'
        depends_on: 
            - surfshark
        network_mode: service:surfshark
        restart: always
    transmission:
        image: linuxserver/transmission
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Rome
            - USER=********************
            - PASS=*******************
            - PEERPORT=4444
        #ports:
         #   - 9091: 9091 #needed to access transmission's GUI
        volumes:
            - /home/shak/container-program-files/fileserver_share_files/plex:/downloads
        network_mode: service:surfshark
        restart: unless-stopped
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /home/shak/container-program-files/fileserver_share_files/plex:/config
            - /home/shak/container-program-files/fileserver_share_files/plex/tvseries:/tv #optional
        network_mode: service:surfshark
        restart: unless-stopped
